### ISSUE TITLE
5.2.2 says it's version 5.0.0?

### ISSUE THREAD

**Issue by OneCricketeer** [rycus86/docker-grafana#1]
On Raspberry Pi

```
$ docker run --rm -p 3000:3000 rycus86/grafana:5.2.2-armhf
t=2018-08-06T04:46:27+0000 lvl=info msg="Starting Grafana" logger=server version=5.0.0 commit=NA
```

Meanwhile, on Mac

```
$ docker run --rm -p 3000:3000 grafana/grafana:5.2.2
t=2018-08-06T04:48:19+0000 lvl=info msg="Starting Grafana" logger=server version=5.2.2 commit=aeaf7b2 compiled=2018-07-25T11:17:28+0000
```

**Comment by rycus86** [comment]
Good spot, thanks!
I have seen it before, let me just try to dig out from the Grafana source code how the version number is passed to it.

**Comment by OneCricketeer** [comment]
Poking around in the UI, I didn't spot any differences, so it's probably an issue in Grafana source, as you say.

**Comment by rycus86** [comment]
Thanks for checking!
I made some progress, though still don't know how to get the correct version number set when building from source - it looks like it's hardcoded in the source code.

I just noticed though, that Grafana now distributes official ARM builds: https://grafana.com/grafana/download/5.2.2?platform=arm

I'm going to set up a build for this for testing.

**Comment by rycus86** [comment]
OK, this should do it: https://github.com/rycus86/docker-grafana/compare/5.2.2...master :tada: 

Thanks again for opening this issue!

**Comment by OneCricketeer** [comment]
➕ 💯 For cleaner Dockerfiles 😄
